[tool.poetry]
name = "zenml-experiments"
version = "0.1.0"
description = ""
authors = ["azza <azza.baatout@adesso.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
zenml = "^0.58.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
